# ---------------------------------------------------------------------------- #

[tool.black]

force-exclude = "/tuichain_ethereum/_contracts.py"
line-length = 80
target-version = [ "py38" ]

# ---------------------------------------------------------------------------- #

[tool.tox]

legacy_tox_ini = """
[tox]
envlist = py38,py39

[testenv]
install_command =
    python -m pip install {opts} --use-feature=2020-resolver {packages}
extras =
    test
commands =
    mypy
    black --check setup.py test tuichain_ethereum
    pytest test
"""

# ---------------------------------------------------------------------------- #
